DROP TABLE CATEGORIES IF EXISTS;
CREATE TABLE CATEGORIES(category_id INT PRIMARY_KEY AUTO_INCREMENT,category_name VARCHAR(100));

DROP TABLE BRANDS IF EXISTS;
CREATE TABLE BRANDS(brand_id INT PRIMARY_KEY AUTO_INCREMENT,brand_name VARCHAR(100));