DROP TABLE CATEGORIES IF EXISTS;
CREATE TABLE CATEGORIES(category_id INT AUTO_INCREMENT PRIMARY_KEY,category_name VARCHAR(100));

DROP TABLE BRANDS IF EXISTS;
CREATE TABLE BRANDS(brand_id INT AUTO_INCREMENT PRIMARY KEY,brand_name VARCHAR(100));